### ISSUE TITLE
Use Case: As a user, I want to see my transactions

### ISSUE THREAD

**Issue by yg-apaza** [lagom/online-auction-java#107]
This is based on Item service implementation

- [x] Add service call `getTransactionsForUser` and TransactionRepository (#106)
- [x] Add tests: `TransactionRepositoryTest` (#106)
- [x] web-gateway: Show transactions on `/my/transactions` (#135)

Although it's not related, this task is pending:
- [x] Ensure that  `exception.getCause()` in [this line](https://github.com/lagom/online-auction-java/blob/master/web-gateway/src/main/java/controllers/TransactionController.java#L135) will always be a `TransportException` ([see this](https://github.com/lagom/online-auction-java/pull/94#discussion_r123225622))

**Comment by ignasi35** [comment]
>  web-gateway: Show transactions on /my/transactions/:status

Would it make sense filter by other criteria? (date, creator VS winner, etc...)
If so, I think filtering criteria should be passed as query params instead of pathParams, WDYT?

**Comment by yg-apaza** [comment]
I agree, the filter criteria will be: status, date, and type. As for the date, I will need to store `auctionEnd` of `AuctionFinished` event in `Transaction`

**Comment by yg-apaza** [comment]
All pending tasks have been completed, I'll let the filter by other criteria as future improvements.
